package injector

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type goldenVector struct {
	Name        string `json:"name"`
	Rnd         string `json:"rnd"`
	SessID      string `json:"sess_id"`
	SNI         string `json:"sni"`
	KeyShare    string `json:"key_share"`
	ExpectedHex string `json:"expected_hex"`
	ExpectedLen int    `json:"expected_len"`
}

type goldenFile struct {
	Version int            `json:"version"`
	Vectors []goldenVector `json:"vectors"`
}

// TestClientHelloGolden verifies byte-for-byte parity with the upstream
// Python ClientHelloMaker. Vectors are generated by test/golden/gen_golden.py.
func TestClientHelloGolden(t *testing.T) {
	path := filepath.Join("..", "..", "test", "golden", "clienthello_golden.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var gf goldenFile
	if err := json.Unmarshal(raw, &gf); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(gf.Vectors) == 0 {
		t.Fatal("no golden vectors")
	}

	for _, v := range gf.Vectors {
		v := v
		t.Run(v.Name, func(t *testing.T) {
			rnd, _ := hex.DecodeString(v.Rnd)
			sess, _ := hex.DecodeString(v.SessID)
			ks, _ := hex.DecodeString(v.KeyShare)
			got, err := BuildClientHello(rnd, sess, []byte(v.SNI), ks)
			if err != nil {
				t.Fatalf("BuildClientHello: %v", err)
			}
			if len(got) != v.ExpectedLen {
				t.Fatalf("len: got %d want %d", len(got), v.ExpectedLen)
			}
			want, _ := hex.DecodeString(v.ExpectedHex)
			if hex.EncodeToString(got) != v.ExpectedHex {
				t.Fatalf("byte mismatch\n got:  %x\n want: %x", got, want)
			}
		})
	}
}

func TestClientHelloRejectsBadInput(t *testing.T) {
	bad31 := make([]byte, 31)
	good := make([]byte, 32)
	longSNI := make([]byte, 220)

	cases := []struct {
		name                   string
		rnd, sess, sni, keyShr []byte
	}{
		{"short_rnd", bad31, good, []byte("x"), good},
		{"short_sess", good, bad31, []byte("x"), good},
		{"short_keyshare", good, good, []byte("x"), bad31},
		{"oversize_sni", good, good, longSNI, good},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			if _, err := BuildClientHello(c.rnd, c.sess, c.sni, c.keyShr); err == nil {
				t.Fatal("expected error")
			}
		})
	}
}

func BenchmarkBuildClientHello(b *testing.B) {
	rnd := make([]byte, 32)
	sess := make([]byte, 32)
	ks := make([]byte, 32)
	sni := []byte("auth.vercel.com")
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		if _, err := BuildClientHello(rnd, sess, sni, ks); err != nil {
			b.Fatal(err)
		}
	}
}
